---
title: "Data_import_tibble"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r results='hide'}
datasets::iris
iris
```

```{r}
write.csv(iris, file="iris.csv")
iris2 <-read.csv(file="iris.csv", header=TRUE, sep = ",")
write.csv(iris,file="iris.csv",row.names = FALSE)
iris3 <-read.csv(file="iris.csv", header=TRUE, sep = ",")
#read.table
```

```{r}
head(iris$Species)
head(iris[,5])
```


```{r}
url <- "https://www.iun.edu/~cisjw/ds/files/data/weather.csv"
weather <- read.csv(url)
```


## readr
reference: <https://www.iun.edu/~cisjw/ds/files/practice-1.html#6_data_import>
```{r}
weather.tibble <- read_csv(url, na = "n/a")
```

## tibble with dplyr

```{r}
iris.tib<- read_csv("iris.csv")
#dplyr
iris.tib %>% 
  select(1,3) %>% 
  top_n(5)

iris.tib %>% select_if(is.numeric)  %>% top_n(5)
iris.tib %>% select_if(negate(is.numeric))%>% top_n(5)
```

## summarise 


### summary function
```{r}
summary(iris)
```

## dplyr::summarise 
ref: <https://www.iun.edu/~cisjw/ds/files/script/project/summarise_function.R>
```{r}
iris %>% summarise(mean(Sepal.Length))
iris %>% summarise(mean(Sepal.Length),sd(Sepal.Length))
```



## Data normalization

<https://www.iun.edu/~cisjw/ds/files/practice-1.html#7_data_normalization>